### ISSUE TITLE
403 errors in episode links

### ISSUE THREAD

**Issue by tshrpl** [tarunm20/4anime-scraper#3] opened 2020-10-23 11:37 UTC
test file:
```js
user@Notebook:~/desktop/4anime_scraper_test_2$ cat blah.js

const Anime = require('4anime-scraper').default;
Anime.getVideoLinkFromUrl("https://4anime.to/himegoto-episode-01?id=28984")
	.then(res => {
		console.log(res);
	});
```

output:
```bash
user@Notebook:~/desktop/4anime_scraper_test_2$ node blah.js > link
user@Notebook:~/desktop/4anime_scraper_test_2$ curl $(cat link)
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by tarunm20** [comment] 2020-10-23 12:35
Hey tshrpl, 

Thank you for the error notice. From what I can tell, the error is related to accessing the url that is returned from the getVideoLinkFromURL() function. The problem is that when sending the request there isn't proper authentication which results in the 403. I tested with other episodes as well and the same problem occurred.

If you're looking for a package that can download episodes then this one doesn't have that capability but if you're looking for specific information regarding the episode such as comments regarding the episode I will add that to the package.

**Comment by tshrpl** [comment] 2020-10-23 14:14
many users on the 4anime [discord server](https://discord.gg/TzuEpf8) are getting 403 errors (from 4anime.me servers). seems like the site is under heavy load.

but that's not true for the newer episodes which are hosted on google cloud storages. so newer episodes can easily be downloaded without any problems
```js
Anime.getVideoLinkFromUrl("https://4anime.to/d4dj-first-mix-episode-01?id=43636") // new episode example
```

**Comment by tshrpl** [comment] 2020-10-23 14:18
will close this issue later, after one last update, because the errors are not related to the package itself

**Comment by tarunm20** [comment] 2020-10-23 14:28
I didn't know about 4anime's move to google cloud storage. Could you send an example I would like to try creating a video downloader that supports the new links.

**Comment by tshrpl** [comment] 2020-10-23 14:43
the migration has not affected the code, I've tested and it still works.

but still leaving this from my python scraper
```<source src="(.*)".*/>``` -> `\1` spits out the direct links

**Comment by tarunm20** [comment] 2020-10-23 22:11
I found a workaround for the problem you were facing with the video link returning a 403. Since 4anime.to is moving to google storage, using the URL like so: 

https://storage.googleapis.com/justawesome-183319.appspot.com/v1.4animu.me/Himegoto/Himegoto-Episode-01-1080p.mp4?md5=GrdjGFnjPRBe8A0e-01LPw&expires=1603504770

returns a valid response. Just adding "https://storage.googleapis.com/justawesome-183319.appspot.com" to the front of any URLs returned from the getVideoLinkFromUrl(episodeUrl) function.

I'm currently working on a function in the scraper package that takes in a video link and downloads it to a path so if that's what you're looking for then that functionality will be available.

**Comment by tshrpl** [comment] 2020-10-23 22:42
i already said but i will repeat again, the code in the package works just fine, the 403 errors were because 4anime was migrating from its own hosted servers to google cloud, and just using a regex would be cleaner and faster in my oppinion

i dont think download function is necessary but it would be really cool if the package has a function, it'll save me some bash scripts and server side debugging lol

thanks again :)

**Comment by tshrpl** [comment] 2020-10-23 23:23
just noticed another thing
the direct link generated from this url gives 403 errors `https://4anime.to/bakemonogatari-episode-01?id=20143`
but removing `?id=20143` parameter from the url solves this issue, you can add this feature into the `getVideoLinkFromUrl` function (to remove id parameter)

**Comment by tarunm20** [comment] 2020-10-24 08:33
That's a nice find, I'll make the change and add the video download function asap.

**Closed** 2020-10-30 15:42 UTC
